const categoriesData = {
  categories: [
    {
      id: 1,
      name: 'Cups',
      url: '/categories/cups',
      image_url: '/assets/categories/Cups.png',
      description: 'Variety of cups in all shapes and sizes',
      subCategories: [
        {
          id: 1,
          name: 'Stanleys',
          url: '/categories/cups/stanleys',
          image_url: '/assets/subcategories/Adult Stanleys.avif',
          description: 'Stanley Dupes in Various Colours',
          products: [
            {
              id: 1,
              name: 'Adults',
              stock: 0,
              price: 10,
              image_url: '/assets/placeholder.png',
              description: 'placeholder, placeholder, placeholder',
            },
            {
              id: 2,
              name: 'Kids',
              stock: 0,
              price: 10,
              image_url: '/assets/placeholder.png',
              description: 'placeholder, placeholder, placeholder',
            },
          ],
        },
        {
          id: 2,
          name: 'Libbeys',
          url: '/categories/cups/libbeys',
          image_url: '/assets/subcategories/libbeys.jfif',
          description: 'placeholder, placeholder, placeholder',
          products: [
            {
              id: 1,
              name: 'Placeholder 1',
              stock: 0,
              price: 10,
              image_url: '/assets/placeholder.png',
              description: 'placeholder, placeholder, placeholder',
            },
            {
              id: 2,
              name: 'Placeholder 2',
              stock: 0,
              price: 10,
              image_url: '/assets/placeholder.png',
              description: 'placeholder, placeholder, placeholder',
            },
          ],
        },
        {
          id: 3,
          name: 'Cold Cups',
          url: '/categories/cups/coldcups',
          image_url: '/assets/subcategories/24oz Cold Cups.jpg',
          description: 'placeholder, placeholder, placeholder',
          products: [
            {
              id: 1,
              name: 'Placeholder 1',
              stock: 0,
              price: 10,
              image_url: '/assets/placeholder.png',
              description: 'placeholder, placeholder, placeholder',
            },
            {
              id: 2,
              name: 'Placeholder 2',
              stock: 0,
              price: 10,
              image_url: '/assets/placeholder.png',
              description: 'placeholder, placeholder, placeholder',
            },
          ],
        },
        {
          id: 4,
          name: 'Tumblers',
          url: '/categories/cups/tumblers',
          image_url: '/assets/subcategories/Glass Tumblrs 16oz.webp',
          description: 'placeholder, placeholder, placeholder',
          products: [
            {
              id: 1,
              name: 'Placeholder 1',
              stock: 0,
              price: 10,
              image_url: '/assets/placeholder.png',
              description: 'placeholder, placeholder, placeholder',
            },
            {
              id: 2,
              name: 'Placeholder 2',
              stock: 0,
              price: 10,
              image_url: '/assets/placeholder.png',
              description: 'placeholder, placeholder, placeholder',
            },
          ],
        },
        {
          id: 5,
          name: 'Smoothie Cups',
          url: '/categories/cups/smoothiecups',
          image_url: '/assets/subcategories/Smoothie Cups.avif',
          description: 'placeholder, placeholder, placeholder',
          products: [
            {
              id: 1,
              name: 'Placeholder 1',
              stock: 0,
              price: 10,
              image_url: '/assets/placeholder.png',
              description: 'placeholder, placeholder, placeholder',
            },
            {
              id: 2,
              name: 'Placeholder 2',
              stock: 0,
              price: 10,
              image_url: '/assets/placeholder.png',
              description: 'placeholder, placeholder, placeholder',
            },
          ],
        },
      ],
    },
    {
      id: 2,
      name: 'UV DTF Wraps',
      url: '/categories/UV DTF Wraps',
      image_url: '/assets/categories/16oz UV DTF wrap TAY,ERASTOUR.jpg',
      description: '',
      subCategories: [
        {
          id: 1,
          name: '16oz UV DTF wraps',
          url: '/categories/UV DTF Wraps/wraps/',
          image_url: '/assets/subcategories/16oz wraps.webp',
          description: '',
          products: [
            {
              id: 1,
              name: 'Placeholder 1',
              stock: 0,
              price: 10,
              image_url: '/assets/placeholder.png',
              description: 'placeholder, placeholder, placeholder',
            },
          ],
        },
      ],
    },
  ],
};

export default categoriesData;
