const categoriesData = {
  categories: [
    {
      id: 1,
      name: 'Cups',
      url: '/categories/cups',
      image_url: '/assets/categories/Cups.png',
      description: 'Variety of cups in all shapes and sizes',
      subCategories: [
        {
          id: 1,
          name: 'Stanleys',
          url: '/categories/cups/stanleys',
          image_url: '/assets/placeholder.png',
          description: 'placeholder, placeholder, placeholder',
          products: [
            {
              id: 1,
              name: 'Adults',
              stock: 0,
              price: 10,
              image_url: '/assets/placeholder.png',
              description: 'placeholder, placeholder, placeholder',
            },
            {
              id: 2,
              name: 'Kids',
              stock: 0,
              price: 10,
              image_url: '/assets/placeholder.png',
              description: 'placeholder, placeholder, placeholder',
            },
          ],
        },
        {
          id: 2,
          name: 'Libbeys',
          url: '/categories/cups/libbeys',
          image_url: '/assets/placeholder.png',
          description: 'placeholder, placeholder, placeholder',
          products: [
            {
              id: 1,
              name: 'Placeholder 1',
              stock: 0,
              price: 10,
              image_url: '/assets/placeholder.png',
              description: 'placeholder, placeholder, placeholder',
            },
            {
              id: 2,
              name: 'Placeholder 2',
              stock: 0,
              price: 10,
              image_url: '/assets/placeholder.png',
              description: 'placeholder, placeholder, placeholder',
            },
          ],
        },
        {
          id: 3,
          name: 'Cold Cups',
          url: '/categories/cups/coldcups',
          image_url: '/assets/placeholder.png',
          description: 'placeholder, placeholder, placeholder',
          products: [
            {
              id: 1,
              name: 'Placeholder 1',
              stock: 0,
              price: 10,
              image_url: '/assets/placeholder.png',
              description: 'placeholder, placeholder, placeholder',
            },
            {
              id: 2,
              name: 'Placeholder 2',
              stock: 0,
              price: 10,
              image_url: '/assets/placeholder.png',
              description: 'placeholder, placeholder, placeholder',
            },
          ],
        },
        {
          id: 4,
          name: 'Tumblers',
          url: '/categories/cups/tumblers',
          image_url: '/assets/placeholder.png',
          description: 'placeholder, placeholder, placeholder',
          products: [
            {
              id: 1,
              name: 'Placeholder 1',
              stock: 0,
              price: 10,
              image_url: '/assets/placeholder.png',
              description: 'placeholder, placeholder, placeholder',
            },
            {
              id: 2,
              name: 'Placeholder 2',
              stock: 0,
              price: 10,
              image_url: '/assets/placeholder.png',
              description: 'placeholder, placeholder, placeholder',
            },
          ],
        },
        {
          id: 5,
          name: 'Smoothie Cups',
          url: '/categories/cups/smoothiecups',
          image_url: '/assets/placeholder.png',
          description: 'placeholder, placeholder, placeholder',
          products: [
            {
              id: 1,
              name: 'Placeholder 1',
              stock: 0,
              price: 10,
              image_url: '/assets/placeholder.png',
              description: 'placeholder, placeholder, placeholder',
            },
            {
              id: 2,
              name: 'Placeholder 2',
              stock: 0,
              price: 10,
              image_url: '/assets/placeholder.png',
              description: 'placeholder, placeholder, placeholder',
            },
          ],
        },
      ],
    },
    {
      id: 2,
      name: 'Placeholder',
      url: '/categories/placeholder',
      image_url: '/assets/placeholder.png',
      description: 'Variety of cups in all shapes and sizes',
      subCategories: [
        {
          id: 1,
          name: 'Placeholder',
          image_url: '/assets/placeholder.png',
          description: 'placeholder, placeholder, placeholder',
          products: [
            {
              id: 1,
              name: 'Placeholder',
              stock: 0,
              price: 10,
              image_url: '/assets/placeholder.png',
              description: 'placeholder, placeholder, placeholder',
            },
            {
              id: 2,
              name: 'Placeholder',
              stock: 0,
              price: 10,
              image_url: '/assets/placeholder.png',
              description: 'placeholder, placeholder, placeholder',
            },
          ],
        },
        {
          id: 2,
          name: 'Placeholder',
          image_url: '/assets/placeholder.png',
          description: 'placeholder, placeholder, placeholder',
          products: [
            {
              id: 1,
              name: 'Placeholder 1',
              stock: 0,
              price: 10,
              image_url: '/assets/placeholder.png',
              description: 'placeholder, placeholder, placeholder',
            },
            {
              id: 2,
              name: 'Placeholder 2',
              stock: 0,
              price: 10,
              image_url: '/assets/placeholder.png',
              description: 'placeholder, placeholder, placeholder',
            },
          ],
        },
        {
          id: 3,
          name: 'Placeholder',
          image_url: '/assets/placeholder.png',
          description: 'placeholder, placeholder, placeholder',
          products: [
            {
              id: 1,
              name: 'Placeholder 1',
              stock: 0,
              price: 10,
              image_url: '/assets/placeholder.png',
              description: 'placeholder, placeholder, placeholder',
            },
            {
              id: 2,
              name: 'Placeholder 2',
              stock: 0,
              price: 10,
              image_url: '/assets/placeholder.png',
              description: 'placeholder, placeholder, placeholder',
            },
          ],
        },
        {
          id: 4,
          name: 'Placeholder',
          image_url: '/assets/placeholder.png',
          description: 'placeholder, placeholder, placeholder',
          products: [
            {
              id: 1,
              name: 'Placeholder 1',
              stock: 0,
              price: 10,
              image_url: '/assets/placeholder.png',
              description: 'placeholder, placeholder, placeholder',
            },
            {
              id: 2,
              name: 'Placeholder 2',
              stock: 0,
              price: 10,
              image_url: '/assets/placeholder.png',
              description: 'placeholder, placeholder, placeholder',
            },
          ],
        },
        {
          id: 5,
          name: 'Placeholder',
          image_url: '/assets/placeholder.png',
          description: 'placeholder, placeholder, placeholder',
          products: [
            {
              id: 1,
              name: 'Placeholder 1',
              stock: 0,
              price: 10,
              image_url: '/assets/placeholder.png',
              description: 'placeholder, placeholder, placeholder',
            },
            {
              id: 2,
              name: 'Placeholder 2',
              stock: 0,
              price: 10,
              image_url: '/assets/placeholder.png',
              description: 'placeholder, placeholder, placeholder',
            },
          ],
        },
      ],
    },
    {
      id: 3,
      name: 'Placeholder',
      image_url: '/assets/placeholder.png',
      url: '/categories/cups',
      description: 'Variety of cups in all shapes and sizes',
      subCategories: [
        {
          id: 1,
          name: 'Placeholder',
          image_url: '/assets/placeholder.png',
          description: 'placeholder, placeholder, placeholder',
          products: [
            {
              id: 1,
              name: 'Placeholder',
              stock: 0,
              price: 10,
              image_url: '/assets/placeholder.png',
              description: 'placeholder, placeholder, placeholder',
            },
            {
              id: 2,
              name: 'Placeholder',
              stock: 0,
              price: 10,
              image_url: '/assets/placeholder.png',
              description: 'placeholder, placeholder, placeholder',
            },
          ],
        },
        {
          id: 2,
          name: 'Placeholder',
          image_url: '/assets/placeholder.png',
          description: 'placeholder, placeholder, placeholder',
          products: [
            {
              id: 1,
              name: 'Placeholder 1',
              stock: 0,
              price: 10,
              image_url: '/assets/placeholder.png',
              description: 'placeholder, placeholder, placeholder',
            },
            {
              id: 2,
              name: 'Placeholder 2',
              stock: 0,
              price: 10,
              image_url: '/assets/placeholder.png',
              description: 'placeholder, placeholder, placeholder',
            },
          ],
        },
        {
          id: 3,
          name: 'Placeholder',
          image_url: '/assets/placeholder.png',
          description: 'placeholder, placeholder, placeholder',
          products: [
            {
              id: 1,
              name: 'Placeholder 1',
              stock: 0,
              price: 10,
              image_url: '/assets/placeholder.png',
              description: 'placeholder, placeholder, placeholder',
            },
            {
              id: 2,
              name: 'Placeholder 2',
              stock: 0,
              price: 10,
              image_url: '/assets/placeholder.png',
              description: 'placeholder, placeholder, placeholder',
            },
          ],
        },
        {
          id: 4,
          name: 'Placeholder',
          image_url: '/assets/placeholder.png',
          description: 'placeholder, placeholder, placeholder',
          products: [
            {
              id: 1,
              name: 'Placeholder 1',
              stock: 0,
              price: 10,
              image_url: '/assets/placeholder.png',
              description: 'placeholder, placeholder, placeholder',
            },
            {
              id: 2,
              name: 'Placeholder 2',
              stock: 0,
              price: 10,
              image_url: '/assets/placeholder.png',
              description: 'placeholder, placeholder, placeholder',
            },
          ],
        },
        {
          id: 5,
          name: 'Placeholder',
          image_url: '/assets/placeholder.png',
          description: 'placeholder, placeholder, placeholder',
          products: [
            {
              id: 1,
              name: 'Placeholder 1',
              stock: 0,
              price: 10,
              image_url: '/assets/placeholder.png',
              description: 'placeholder, placeholder, placeholder',
            },
            {
              id: 2,
              name: 'Placeholder 2',
              stock: 0,
              price: 10,
              image_url: '/assets/placeholder.png',
              description: 'placeholder, placeholder, placeholder',
            },
          ],
        },
      ],
    },
  ],
};

export default categoriesData;
